import { Process, MemoryNode } from '@/types/memory';

export const processes: Process[] = [
  {
    name: 'svchost.exe',
    pid: 1247,
    icon: 'Settings',
    isDangerous: false,
  },
  {
    name: 'csgo.exe',
    pid: 8542,
    icon: 'Gamepad2',
    isDangerous: false,
  },
  {
    name: 'Minecraft.Windows.exe',
    pid: 3901,
    icon: 'Box',
    isDangerous: true,
  },
];

export const generateMemoryTree = (processName: string): MemoryNode => {
  const baseAddresses = {
    'svchost.exe': '0x7FF80C5A0000',
    'csgo.exe': '0x08595760',
    'Minecraft.Windows.exe': '0x14002B000',
  };

  const trees = {
    'svchost.exe': createSvchostTree(),
    'csgo.exe': createCSGOTree(),
    'Minecraft.Windows.exe': createMinecraftTree(),
  };

  return {
    id: 'root',
    name: processName,
    offset: baseAddresses[processName as keyof typeof baseAddresses] || '0x00000000',
    icon: 'Cpu',
    color: 'text-primary-purple',
    children: trees[processName as keyof typeof trees] || [],
    isExpanded: true,
  };
};

function createCSGOTree(): MemoryNode[] {
  return [
    {
      id: 'world',
      name: 'World',
      offset: '+0x158',
      icon: 'Globe',
      color: 'text-accent-mint',
      isExpanded: true,
      children: [
        {
          id: 'timer',
          name: 'Timer',
          offset: '+0x8',
          icon: 'Clock',
          color: 'text-secondary-pink',
          value: 1.5,
          valueType: 'float',
          description: 'Game speed multiplier',
        },
        {
          id: 'mapdata',
          name: 'MapData',
          offset: '+0x24',
          icon: 'Map',
          color: 'text-yellow-500',
          isExpanded: false,
          children: [
            {
              id: 'mapname',
              name: 'MapName',
              offset: '+0x14',
              icon: 'Type',
              color: 'text-blue-500',
              value: 'de_dust2',
              valueType: 'string',
            },
            {
              id: 'spawnpoints',
              name: 'SpawnPoints',
              offset: '+0x30',
              icon: 'Target',
              color: 'text-green-500',
              value: 'Array[16]',
              valueType: 'Array',
            },
          ],
        },
      ],
    },
    {
      id: 'entitylist',
      name: 'EntityList',
      offset: '+0x4DC',
      icon: 'Users',
      color: 'text-blue-500',
      isExpanded: true,
      children: [
        {
          id: 'localplayer',
          name: 'LocalPlayer',
          offset: '+0x10',
          icon: 'User',
          color: 'text-primary-purple',
          isExpanded: true,
          children: [
            {
              id: 'health',
              name: 'Health',
              offset: '+0x100',
              icon: 'Heart',
              color: 'text-danger-red',
              value: 100,
              valueType: 'int32',
              description: 'Current player health',
            },
            {
              id: 'position',
              name: 'Position',
              offset: '+0x138',
              icon: 'Crosshair',
              color: 'text-accent-mint',
              value: { x: 1247.52, y: -384.01, z: 128.75 },
              valueType: 'Vec3',
              description: 'World coordinates',
            },
            {
              id: 'armor',
              name: 'Armor',
              offset: '+0x117',
              icon: 'Shield',
              color: 'text-blue-500',
              isExpanded: false,
              children: [
                {
                  id: 'armorvalue',
                  name: 'ArmorValue',
                  offset: '+0x4',
                  icon: 'ShieldCheck',
                  color: 'text-blue-600',
                  value: 87,
                  valueType: 'int32',
                },
              ],
            },
          ],
        },
        {
          id: 'enemies',
          name: 'Enemies',
          offset: '+0x40',
          icon: 'Users',
          color: 'text-orange-500',
          value: 'Array[10]',
          valueType: 'Array',
          isExpanded: false,
        },
      ],
    },
    {
      id: 'resources',
      name: 'Resources',
      offset: '+0x2A8',
      icon: 'Database',
      color: 'text-purple-500',
      isExpanded: false,
      children: [
        {
          id: 'money',
          name: 'Money',
          offset: '+0x40',
          icon: 'DollarSign',
          color: 'text-green-500',
          value: 16000,
          valueType: 'int32',
        },
        {
          id: 'rounds',
          name: 'RoundInfo',
          offset: '+0x8C',
          icon: 'Timer',
          color: 'text-yellow-500',
          isExpanded: false,
        },
      ],
    },
  ];
}

function createMinecraftTree(): MemoryNode[] {
  return [
    {
      id: 'world',
      name: 'World',
      offset: '+0x50',
      icon: 'Globe',
      color: 'text-accent-mint',
      isExpanded: false,
      children: [
        {
          id: 'time',
          name: 'Time',
          offset: '+0x30',
          icon: 'Sun',
          color: 'text-yellow-500',
          value: 6000,
          valueType: 'int32',
          description: 'Game time in ticks',
        },
        {
          id: 'difficulty',
          name: 'Difficulty',
          offset: '+0x34',
          icon: 'Zap',
          color: 'text-red-500',
          value: 2,
          valueType: 'int32',
          description: 'Normal difficulty',
        },
        {
          id: 'seed',
          name: 'WorldSeed',
          offset: '+0x38',
          icon: 'Sprout',
          color: 'text-green-600',
          value: -1234567890,
          valueType: 'int32',
          description: 'World generation seed',
        },
      ],
    },
    {
      id: 'entityList',
      name: 'EntityList',
      offset: '+0xA0',
      icon: 'Users',
      color: 'text-blue-500',
      isExpanded: false,
      children: [
        {
          id: 'localPlayer',
          name: 'LocalPlayer',
          offset: '+0x18',
          icon: 'User',
          color: 'text-primary-purple',
          isExpanded: false,
          children: [
            {
              id: 'inventory',
              name: 'Inventory',
              offset: '+0x20',
              icon: 'Package',
              color: 'text-blue-500',
              isExpanded: false,
              children: [
                {
                  id: 'playerHotbar',
                  name: 'Hotbar',
                  offset: '+0x10',
                  icon: 'Layout',
                  color: 'text-green-500',
                  value: 'Array[9]',
                  valueType: 'Array',
                  description: 'Player hotbar slots',
                },
                {
                  id: 'playerMainInventory',
                  name: 'MainInventory',
                  offset: '+0x24',
                  icon: 'Package',
                  color: 'text-blue-600',
                  value: 'Array[27]',
                  valueType: 'Array',
                  description: 'Main inventory slots',
                },
                {
                  id: 'playerArmor',
                  name: 'ArmorSlots',
                  offset: '+0x38',
                  icon: 'Shield',
                  color: 'text-purple-500',
                  value: 'Array[4]',
                  valueType: 'Array',
                  description: 'Equipped armor pieces',
                },
                {
                  id: 'playerOffhand',
                  name: 'OffhandSlot',
                  offset: '+0x4C',
                  icon: 'Hand',
                  color: 'text-orange-500',
                  value: 'minecraft:shield',
                  valueType: 'string',
                  description: 'Item in off-hand slot',
                },
              ],
            },
            {
              id: 'reach',
              name: 'Reach',
              offset: '+0x2C',
              icon: 'Target',
              color: 'text-orange-500',
              value: 3.5,
              valueType: 'float',
              description: 'Player reach distance in blocks',
            },
            {
              id: 'velocity',
              name: 'Velocity',
              offset: '+0x30',
              icon: 'Zap',
              color: 'text-yellow-500',
              value: { x: 0.12, y: -0.08, z: 0.45 },
              valueType: 'Vec3',
              description: 'Current movement velocity',
            },
            {
              id: 'positionX',
              name: 'Position X',
              offset: '+0x44',
              icon: 'MapPin',
              color: 'text-red-400',
              value: 64.52341,
              valueType: 'float',
              description: 'X coordinate in world space',
            },
            {
              id: 'positionY',
              name: 'Position Y',
              offset: '+0x48',
              icon: 'MapPin',
              color: 'text-green-400',
              value: 71.00125,
              valueType: 'float',
              description: 'Y coordinate (height) in world space',
            },
            {
              id: 'positionZ',
              name: 'Position Z',
              offset: '+0x4C',
              icon: 'MapPin',
              color: 'text-blue-400',
              value: -128.3847,
              valueType: 'float',
              description: 'Z coordinate in world space',
            },
            {
              id: 'timer',
              name: 'Timer',
              offset: '+0x50',
              icon: 'Clock',
              color: 'text-purple-500',
              value: 20,
              valueType: 'int32',
              description: 'Game tick timer',
            },
            {
              id: 'speed',
              name: 'Speed',
              offset: '+0x54',
              icon: 'Gauge',
              color: 'text-cyan-400',
              value: 4.317,
              valueType: 'float',
              description: 'Current movement speed in m/s',
            },
            {
              id: 'rotation',
              name: 'Rotation',
              offset: '+0x58',
              icon: 'RotateCw',
              color: 'text-indigo-400',
              value: { x: -12.5, y: 147.8, z: 0.0 },
              valueType: 'Vec3',
              description: 'Player rotation angles (pitch, yaw, roll)',
            },
            {
              id: 'onGround',
              name: 'OnGround',
              offset: '+0x64',
              icon: 'Anchor',
              color: 'text-brown-500',
              value: true,
              valueType: 'int32',
              description: 'Whether player is touching ground',
            },
            {
              id: 'jumpHeight',
              name: 'JumpHeight',
              offset: '+0x68',
              icon: 'ArrowUp',
              color: 'text-green-300',
              value: 1.25,
              valueType: 'float',
              description: 'Maximum jump height in blocks',
            },
            {
              id: 'fallDistance',
              name: 'FallDistance',
              offset: '+0x6C',
              icon: 'ArrowDown',
              color: 'text-red-300',
              value: 0.0,
              valueType: 'float',
              description: 'Distance fallen without touching ground',
            },
            {
              id: 'stamina',
              name: 'Stamina',
              offset: '+0x70',
              icon: 'Battery',
              color: 'text-yellow-400',
              value: 18.7,
              valueType: 'float',
              description: 'Player stamina/energy level',
            },
            {
              id: 'attackCooldown',
              name: 'AttackCooldown',
              offset: '+0x74',
              icon: 'Sword',
              color: 'text-red-600',
              value: 0.0,
              valueType: 'float',
              description: 'Time until next attack possible',
            },
            {
              id: 'gameMode',
              name: 'GameMode',
              offset: '+0x78',
              icon: 'Settings',
              color: 'text-gray-500',
              value: 1,
              valueType: 'int32',
              description: 'Current game mode (0=Survival, 1=Creative)',
            },

            {
              id: 'playerHealth',
              name: 'Health',
              offset: '+0xB0',
              icon: 'Heart',
              color: 'text-danger-red',
              value: 20.0,
              valueType: 'float',
              description: 'Current health points',
            },
            {
              id: 'hunger',
              name: 'Hunger',
              offset: '+0xB4',
              icon: 'Utensils',
              color: 'text-yellow-600',
              value: 18,
              valueType: 'int32',
              description: 'Food level',
            },
            {
              id: 'experience',
              name: 'Experience',
              offset: '+0xB8',
              icon: 'Star',
              color: 'text-green-400',
              value: 847,
              valueType: 'int32',
              description: 'Total XP points',
            },
          ],
        },
        {
          id: 'entities',
          name: 'NearbyEntities',
          offset: '+0x80',
          icon: 'Users',
          color: 'text-orange-400',
          isExpanded: false,
          children: [
            {
              id: 'entityCount',
              name: 'EntityCount',
              offset: '+0x4',
              icon: 'Hash',
              color: 'text-blue-300',
              value: 47,
              valueType: 'int32',
              description: 'Number of entities in loaded chunks',
            },
            {
              id: 'mobsArray',
              name: 'MobsArray',
              offset: '+0x8',
              icon: 'Users',
              color: 'text-green-300',
              value: 'Array[64]',
              valueType: 'Array',
              description: 'Array of nearby mob entities',
            },
            {
              id: 'playersArray',
              name: 'PlayersArray',
              offset: '+0x48',
              icon: 'User',
              color: 'text-purple-300',
              value: 'Array[16]',
              valueType: 'Array',
              description: 'Array of nearby player entities',
            },
          ],
        },
      ],
    },
    {
      id: 'resources',
      name: 'Resources',
      offset: '+0x120',
      icon: 'Database',
      color: 'text-purple-500',
      isExpanded: false,
      children: [
        {
          id: 'textures',
          name: 'TextureManager',
          offset: '+0x28',
          icon: 'Image',
          color: 'text-blue-500',
          isExpanded: false,
          children: [
            {
              id: 'atlasSize',
              name: 'AtlasSize',
              offset: '+0x10',
              icon: 'Square',
              color: 'text-blue-400',
              value: { x: 1024, y: 1024, z: 0 },
              valueType: 'Vec3',
              description: 'Texture atlas dimensions',
            },
            {
              id: 'loadedTextures',
              name: 'LoadedTextures',
              offset: '+0x18',
              icon: 'Layers',
              color: 'text-green-500',
              value: 2847,
              valueType: 'int32',
              description: 'Number of loaded textures',
            },
            {
              id: 'memoryUsage',
              name: 'MemoryUsage',
              offset: '+0x1C',
              icon: 'MemoryStick',
              color: 'text-orange-500',
              value: 156.7,
              valueType: 'float',
              description: 'VRAM usage in MB',
            },
          ],
        },
        {
          id: 'sounds',
          name: 'SoundEngine',
          offset: '+0x44',
          icon: 'Volume2',
          color: 'text-purple-400',
          isExpanded: false,
          children: [
            {
              id: 'activeSounds',
              name: 'ActiveSounds',
              offset: '+0x8',
              icon: 'Play',
              color: 'text-green-400',
              value: 47,
              valueType: 'int32',
              description: 'Currently playing sounds',
            },
            {
              id: 'masterVolume',
              name: 'MasterVolume',
              offset: '+0xC',
              icon: 'VolumeX',
              color: 'text-blue-400',
              value: 0.75,
              valueType: 'float',
              description: 'Master volume level',
            },
            {
              id: 'audioBuffer',
              name: 'AudioBuffer',
              offset: '+0x14',
              icon: 'Radio',
              color: 'text-purple-300',
              value: 'Array[4096]',
              valueType: 'Array',
              description: 'Audio sample buffer',
            },
          ],
        },
        {
          id: 'models',
          name: 'ModelRegistry',
          offset: '+0x60',
          icon: 'Box',
          color: 'text-cyan-500',
          isExpanded: false,
          children: [
            {
              id: 'blockModels',
              name: 'BlockModels',
              offset: '+0x10',
              icon: 'Boxes',
              color: 'text-brown-500',
              value: 1247,
              valueType: 'int32',
              description: 'Loaded block models',
            },
            {
              id: 'entityModels',
              name: 'EntityModels',
              offset: '+0x14',
              icon: 'Users',
              color: 'text-green-400',
              value: 389,
              valueType: 'int32',
              description: 'Entity model count',
            },
          ],
        },
      ],
    },
    {
      id: 'signatures',
      name: 'Signatures',
      offset: '+0x1A0',
      icon: 'FileSignature',
      color: 'text-red-500',
      isExpanded: false,
      children: [
        {
          id: 'codeSignature',
          name: 'CodeSignature',
          offset: '+0x18',
          icon: 'Key',
          color: 'text-red-400',
          isExpanded: false,
          children: [
            {
              id: 'signatureValid',
              name: 'SignatureValid',
              offset: '+0x4',
              icon: 'CheckCircle',
              color: 'text-green-500',
              value: true,
              valueType: 'int32',
              description: 'Digital signature validation',
            },
            {
              id: 'signatureHash',
              name: 'SignatureHash',
              offset: '+0x8',
              icon: 'Hash',
              color: 'text-blue-400',
              value: 'SHA256:a1b2c3...',
              valueType: 'string',
              description: 'Signature hash value',
            },
            {
              id: 'certificateChain',
              name: 'CertificateChain',
              offset: '+0x20',
              icon: 'Link',
              color: 'text-purple-400',
              value: 'Array[3]',
              valueType: 'Array',
              description: 'Certificate chain length',
            },
          ],
        },
        {
          id: 'antiTamper',
          name: 'AntiTamper',
          offset: '+0x34',
          icon: 'Shield',
          color: 'text-orange-500',
          isExpanded: false,
          children: [
            {
              id: 'checksumValid',
              name: 'ChecksumValid',
              offset: '+0x8',
              icon: 'Checkmark',
              color: 'text-green-400',
              value: true,
              valueType: 'int32',
              description: 'File integrity check',
            },
            {
              id: 'lastCheckTime',
              name: 'LastCheckTime',
              offset: '+0xC',
              icon: 'Clock',
              color: 'text-blue-300',
              value: 1672531200,
              valueType: 'int32',
              description: 'Unix timestamp',
            },
          ],
        },
      ],
    },
    {
      id: 'raknet',
      name: 'RakNet',
      offset: '+0x2C0',
      icon: 'Wifi',
      color: 'text-cyan-400',
      isExpanded: false,
      children: [
        {
          id: 'connection',
          name: 'ConnectionManager',
          offset: '+0x20',
          icon: 'Network',
          color: 'text-cyan-300',
          isExpanded: false,
          children: [
            {
              id: 'isConnected',
              name: 'IsConnected',
              offset: '+0x4',
              icon: 'Wifi',
              color: 'text-green-400',
              value: true,
              valueType: 'int32',
              description: 'Network connection status',
            },
            {
              id: 'serverIP',
              name: 'ServerIP',
              offset: '+0x8',
              icon: 'Globe',
              color: 'text-blue-400',
              value: '192.168.1.100',
              valueType: 'string',
              description: 'Connected server IP',
            },
            {
              id: 'serverPort',
              name: 'ServerPort',
              offset: '+0x18',
              icon: 'Hash',
              color: 'text-purple-400',
              value: 19132,
              valueType: 'int32',
              description: 'Server port number',
            },
            {
              id: 'ping',
              name: 'Ping',
              offset: '+0x1C',
              icon: 'Timer',
              color: 'text-yellow-400',
              value: 47,
              valueType: 'int32',
              description: 'Network latency in ms',
            },
          ],
        },
        {
          id: 'packets',
          name: 'PacketManager',
          offset: '+0x44',
          icon: 'Package',
          color: 'text-orange-400',
          isExpanded: false,
          children: [
            {
              id: 'packetsSent',
              name: 'PacketsSent',
              offset: '+0x8',
              icon: 'Send',
              color: 'text-green-300',
              value: 15847,
              valueType: 'int32',
              description: 'Total packets sent',
            },
            {
              id: 'packetsReceived',
              name: 'PacketsReceived',
              offset: '+0xC',
              icon: 'Download',
              color: 'text-blue-300',
              value: 16203,
              valueType: 'int32',
              description: 'Total packets received',
            },
            {
              id: 'packetsLost',
              name: 'PacketsLost',
              offset: '+0x10',
              icon: 'AlertTriangle',
              color: 'text-red-400',
              value: 23,
              valueType: 'int32',
              description: 'Lost packet count',
            },
            {
              id: 'bandwidth',
              name: 'Bandwidth',
              offset: '+0x14',
              icon: 'Gauge',
              color: 'text-purple-300',
              value: 2.47,
              valueType: 'float',
              description: 'Current bandwidth in KB/s',
            },
          ],
        },
        {
          id: 'reliability',
          name: 'ReliabilityLayer',
          offset: '+0x68',
          icon: 'RefreshCw',
          color: 'text-indigo-400',
          isExpanded: false,
          children: [
            {
              id: 'ackQueue',
              name: 'AckQueue',
              offset: '+0x8',
              icon: 'List',
              color: 'text-green-200',
              value: 'Array[128]',
              valueType: 'Array',
              description: 'Acknowledgment queue',
            },
            {
              id: 'resendQueue',
              name: 'ResendQueue',
              offset: '+0x18',
              icon: 'RotateCcw',
              color: 'text-orange-300',
              value: 'Array[64]',
              valueType: 'Array',
              description: 'Packet resend queue',
            },
          ],
        },
      ],
    },
    {
      id: 'cryptographs',
      name: 'Cryptographs',
      offset: '+0x3E0',
      icon: 'Lock',
      color: 'text-yellow-500',
      isExpanded: false,
      children: [
        {
          id: 'encryption',
          name: 'EncryptionManager',
          offset: '+0x28',
          icon: 'Key',
          color: 'text-yellow-400',
          isExpanded: false,
          children: [
            {
              id: 'keySize',
              name: 'KeySize',
              offset: '+0x8',
              icon: 'Hash',
              color: 'text-blue-300',
              value: 256,
              valueType: 'int32',
              description: 'Encryption key size in bits',
            },
            {
              id: 'algorithm',
              name: 'Algorithm',
              offset: '+0xC',
              icon: 'Cpu',
              color: 'text-purple-300',
              value: 'AES-256-GCM',
              valueType: 'string',
              description: 'Encryption algorithm',
            },
            {
              id: 'sessionKey',
              name: 'SessionKey',
              offset: '+0x20',
              icon: 'Key',
              color: 'text-red-300',
              value: 'Array[32]',
              valueType: 'Array',
              description: 'Current session key',
            },
            {
              id: 'ivCounter',
              name: 'IVCounter',
              offset: '+0x40',
              icon: 'RotateCw',
              color: 'text-green-300',
              value: 4729847,
              valueType: 'int32',
              description: 'Initialization vector counter',
            },
          ],
        },
        {
          id: 'hashing',
          name: 'HashManager',
          offset: '+0x4C',
          icon: 'Hash',
          color: 'text-orange-400',
          isExpanded: false,
          children: [
            {
              id: 'hashAlgorithm',
              name: 'HashAlgorithm',
              offset: '+0x8',
              icon: 'Code',
              color: 'text-blue-200',
              value: 'SHA-256',
              valueType: 'string',
              description: 'Hash function in use',
            },
            {
              id: 'saltValue',
              name: 'SaltValue',
              offset: '+0x18',
              icon: 'Shuffle',
              color: 'text-purple-200',
              value: 'Array[16]',
              valueType: 'Array',
              description: 'Cryptographic salt',
            },
            {
              id: 'hashCache',
              name: 'HashCache',
              offset: '+0x28',
              icon: 'Database',
              color: 'text-cyan-200',
              value: 'Array[1024]',
              valueType: 'Array',
              description: 'Cached hash values',
            },
          ],
        },
        {
          id: 'certificates',
          name: 'CertificateStore',
          offset: '+0x70',
          icon: 'Award',
          color: 'text-indigo-300',
          isExpanded: false,
          children: [
            {
              id: 'trustedCerts',
              name: 'TrustedCerts',
              offset: '+0x10',
              icon: 'CheckCircle',
              color: 'text-green-200',
              value: 47,
              valueType: 'int32',
              description: 'Trusted certificate count',
            },
            {
              id: 'clientCert',
              name: 'ClientCert',
              offset: '+0x14',
              icon: 'User',
              color: 'text-blue-200',
              value: 'X509Certificate',
              valueType: 'string',
              description: 'Client certificate type',
            },
            {
              id: 'certExpiry',
              name: 'CertExpiry',
              offset: '+0x28',
              icon: 'Calendar',
              color: 'text-yellow-200',
              value: 1735689600,
              valueType: 'int32',
              description: 'Certificate expiry timestamp',
            },
          ],
        },
      ],
    },
    {
      id: 'rendering',
      name: 'RenderEngine',
      offset: '+0x4F0',
      icon: 'Monitor',
      color: 'text-pink-500',
      isExpanded: false,
      children: [
        {
          id: 'directx',
          name: 'DirectX11',
          offset: '+0x30',
          icon: 'Zap',
          color: 'text-pink-400',
          isExpanded: false,
          children: [
            {
              id: 'deviceContext',
              name: 'DeviceContext',
              offset: '+0x8',
              icon: 'Cpu',
              color: 'text-blue-200',
              value: '0x1A2B3C4D',
              valueType: 'string',
              description: 'D3D11 device context handle',
            },
            {
              id: 'swapChain',
              name: 'SwapChain',
              offset: '+0x10',
              icon: 'RefreshCw',
              color: 'text-green-200',
              value: '0x5E6F7A8B',
              valueType: 'string',
              description: 'DXGI swap chain handle',
            },
            {
              id: 'vsync',
              name: 'VSync',
              offset: '+0x18',
              icon: 'Monitor',
              color: 'text-purple-200',
              value: true,
              valueType: 'int32',
              description: 'Vertical synchronization',
            },
            {
              id: 'frameRate',
              name: 'FrameRate',
              offset: '+0x1C',
              icon: 'Gauge',
              color: 'text-yellow-200',
              value: 144.7,
              valueType: 'float',
              description: 'Current FPS',
            },
          ],
        },
        {
          id: 'shaders',
          name: 'ShaderManager',
          offset: '+0x54',
          icon: 'Palette',
          color: 'text-violet-400',
          isExpanded: false,
          children: [
            {
              id: 'vertexShaders',
              name: 'VertexShaders',
              offset: '+0x8',
              icon: 'Triangle',
              color: 'text-blue-100',
              value: 89,
              valueType: 'int32',
              description: 'Loaded vertex shaders',
            },
            {
              id: 'pixelShaders',
              name: 'PixelShaders',
              offset: '+0xC',
              icon: 'Square',
              color: 'text-red-100',
              value: 127,
              valueType: 'int32',
              description: 'Loaded pixel shaders',
            },
            {
              id: 'computeShaders',
              name: 'ComputeShaders',
              offset: '+0x10',
              icon: 'Zap',
              color: 'text-green-100',
              value: 23,
              valueType: 'int32',
              description: 'Compute shaders loaded',
            },
          ],
        },
      ],
    },
  ];
}

function createSvchostTree(): MemoryNode[] {
  return [
    {
      id: 'service',
      name: 'ServiceInfo',
      offset: '+0x28',
      icon: 'Server',
      color: 'text-blue-500',
      isExpanded: true,
      children: [
        {
          id: 'status',
          name: 'Status',
          offset: '+0x14',
          icon: 'Activity',
          color: 'text-green-500',
          value: 'Running',
          valueType: 'string',
        },
        {
          id: 'pid',
          name: 'ProcessId',
          offset: '+0x8',
          icon: 'Hash',
          color: 'text-gray-500',
          value: 1247,
          valueType: 'int32',
        },
      ],
    },
    {
      id: 'memory',
      name: 'MemoryInfo',
      offset: '+0x70',
      icon: 'MemoryStick',
      color: 'text-purple-500',
      isExpanded: false,
    },
  ];
}
